require("grant.remap")
require("grant.packer")
require("grant.settings")
require("grant.plugin_settings.colourscheme")

require("grant.plugin_settings.nvim-tree")
require("grant.plugin_settings.lsp").setup()
require("grant.plugin_settings.mason")
require("grant.plugin_settings.cmp")
require("grant.plugin_settings.lsp")
-- require("grant.plugin_settings.cmp")
